
CREATE TABLE PARCEL_IN (
	DELIVERY_NUMBER VARCHAR2(100) NOT NULL,
	ENTRY_DATE_TIME DATE NOT NULL,
	RECEIVED_FROM VARCHAR2(100) NOT NULL,
	TO_WHOM VARCHAR2(100) NOT NULL,
	MODE_OF_RECEIPT VARCHAR2(100) NOT NULL,
	DESIGNATION VARCHAR2(100) NOT NULL,
	PHONE_NUMBER NUMBER NOT NULL,
	PARCEL_ID NUMBER NOT NULL,
	CONSTRAINT PARCEL_IN_UNIQUE UNIQUE (DELIVERY_NUMBER),
	CONSTRAINT PARCEL_IN_PK PRIMARY KEY (PARCEL_ID)
);
===================================================================
CREATE SEQUENCE PARCEL_IN_S
  START WITH 1
 INCREMENT BY 1 minvalue 1 maxvalue 9999999999999;
